title: "Relation extraction model"
description: "This project implements a spaCy component with a custom transformders model, which should extract personal relations from english text."

# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  trf_config: "configs/rel_trf.cfg"
  train_file: "data/relations_training.spacy"
  dev_file: "data/relations_dev.spacy"
  test_file: "data/relations_test.spacy"
  trained_model: "training/model-best"
  target_model_name: ""

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["scripts", "configs", "data", "training"]

workflows:
  all:
    - train_cpu
    - evaluate
    - copy_model
  all_gpu:
    - train_gpu
    - evaluate
    - copy_model

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "train_cpu"
    help: "Train the REL model on the CPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.trf_config} --output training --paths.train ${vars.train_file} --paths.dev ${vars.dev_file} -c ./scripts/custom_functions.py"
    deps:
      - ${vars.train_file}
      - ${vars.dev_file}
    outputs:
      - ${vars.trained_model}

  - name: "train_gpu"
    help: "Train the REL model with a Transformer on a GPU and evaluate on the dev corpus."
    script:
      - "python -m spacy train ${vars.trf_config} --output training --paths.train ${vars.train_file} --paths.dev ${vars.dev_file} -c ./scripts/custom_functions.py --gpu-id 0"
    deps:
      - ${vars.train_file}
      - ${vars.dev_file}
    outputs:
      - ${vars.trained_model}

  - name: "evaluate"
    help: "Apply the best model to new, unseen text, and measure accuracy at different thresholds."
    script:
      - "python ./scripts/evaluate.py ${vars.trained_model} ${vars.test_file} False"
    deps:
      - ${vars.trained_model}
      - ${vars.test_file}

  - name: "clean"
    help: "Remove intermediate files to start data preparation and training from a clean slate."
    script:
      - "rm -rf data/*"
      - "rm -rf training/*"

  - name: "copy_model"
    help: "Copies the trained model to the target folder."
    script:
      - "xcopy /s /i training ${vars.target_model_name}"
    deps:
      - ${vars.trained_model}
